/* eslint-disable prettier/prettier */
//  GET_CURRENCY //
export const GET_CURRENCY_REQUEST = 'GET_CURRENCY_REQUEST'
export const GET_CURRENCY_SUCCESS = 'GET_CURRENCY_SUCCESS'
export const GET_CURRENCY_FAILURE = 'GET_CURRENCY_FAILURE'

//  GET_PAIR //
export const GET_PAIR_REQUEST = 'GET_PAIR_REQUEST'
export const GET_PAIR_SUCCESS = 'GET_PAIR_SUCCESS'
export const GET_PAIR_FAILURE = 'GET_PAIR_FAILURE'